[2024-11-26T16:00:26.614+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-26T16:00:26.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-26T16:00:26.638+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T16:00:26.667+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_drift_detected> on 2024-11-25 16:00:00+00:00
[2024-11-26T16:00:26.683+0000] {standard_task_runner.py:57} INFO - Started process 531 to run task
[2024-11-26T16:00:26.690+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'data_drift_detected', 'scheduled__2024-11-25T16:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmpyo_2ijok']
[2024-11-26T16:00:26.695+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask data_drift_detected
[2024-11-26T16:00:26.872+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [running]> on host e76aaec22df7
[2024-11-26T16:00:27.041+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='data_drift_detected' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T16:00:00+00:00'
[2024-11-26T16:00:27.189+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T16:00:27.190+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T16:00:27.197+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T16:00:27.199+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T16:00:27.430+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T16:00:27.431+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T16:00:27.436+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T16:00:27.437+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T16:00:27.870+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-26T16:00:27.890+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=drift_detection_dag, task_id=data_drift_detected, execution_date=20241125T160000, start_date=20241126T160026, end_date=20241126T160027
[2024-11-26T16:00:27.968+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-26T16:00:28.100+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-26T18:43:22.389+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-26T18:43:22.424+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [queued]>
[2024-11-26T18:43:22.424+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T18:43:22.456+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): data_drift_detected> on 2024-11-25 16:00:00+00:00
[2024-11-26T18:43:22.468+0000] {standard_task_runner.py:57} INFO - Started process 290 to run task
[2024-11-26T18:43:22.475+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'data_drift_detected', 'scheduled__2024-11-25T16:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmp2nady41l']
[2024-11-26T18:43:22.479+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask data_drift_detected
[2024-11-26T18:43:22.589+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.data_drift_detected scheduled__2024-11-25T16:00:00+00:00 [running]> on host 88ce0f125f41
[2024-11-26T18:43:22.697+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='data_drift_detected' AIRFLOW_CTX_EXECUTION_DATE='2024-11-25T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-25T16:00:00+00:00'
[2024-11-26T18:43:22.766+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T18:43:22.767+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T18:43:22.772+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T18:43:22.773+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T18:43:22.918+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T18:43:22.919+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T18:43:22.924+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T18:43:22.924+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T18:43:23.149+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-26T18:43:23.159+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=drift_detection_dag, task_id=data_drift_detected, execution_date=20241125T160000, start_date=20241126T184322, end_date=20241126T184323
[2024-11-26T18:43:23.209+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-26T18:43:23.247+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
