[2024-11-26T01:56:14.025+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T01:56:01.497338+00:00 [queued]>
[2024-11-26T01:56:14.036+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T01:56:01.497338+00:00 [queued]>
[2024-11-26T01:56:14.036+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T01:56:14.051+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-11-26 01:56:01.497338+00:00
[2024-11-26T01:56:14.060+0000] {standard_task_runner.py:57} INFO - Started process 8789 to run task
[2024-11-26T01:56:14.064+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_data_drift', 'manual__2024-11-26T01:56:01.497338+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmpfn8q4msg']
[2024-11-26T01:56:14.070+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask detect_data_drift
[2024-11-26T01:56:14.132+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T01:56:01.497338+00:00 [running]> on host 7f10b2294d44
[2024-11-26T01:56:14.223+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_data_drift' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T01:56:01.497338+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T01:56:01.497338+00:00'
[2024-11-26T01:56:14.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T01:56:14.264+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T01:56:14.267+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T01:56:14.268+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T01:56:14.297+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T01:56:14.298+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T01:56:14.300+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T01:56:14.301+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T01:56:14.328+0000] {python.py:194} INFO - Done. Returned value was: data_drift_detected
[2024-11-26T01:56:14.329+0000] {python.py:227} INFO - Branch callable return data_drift_detected
[2024-11-26T01:56:14.329+0000] {skipmixin.py:173} INFO - Following branch data_drift_detected
[2024-11-26T01:56:14.344+0000] {skipmixin.py:239} INFO - Skipping tasks [('no_data_drift_detected', -1)]
[2024-11-26T01:56:14.392+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=drift_detection_dag, task_id=detect_data_drift, execution_date=20241126T015601, start_date=20241126T015614, end_date=20241126T015614
[2024-11-26T01:56:14.437+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-26T01:56:14.475+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
