[2024-11-26T11:59:09.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:58:57.177040+00:00 [queued]>
[2024-11-26T11:59:09.812+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:58:57.177040+00:00 [queued]>
[2024-11-26T11:59:09.813+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T11:59:09.836+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-11-26 11:58:57.177040+00:00
[2024-11-26T11:59:09.848+0000] {standard_task_runner.py:57} INFO - Started process 817 to run task
[2024-11-26T11:59:09.853+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_data_drift', 'manual__2024-11-26T11:58:57.177040+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmpqxbhbtrz']
[2024-11-26T11:59:09.858+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask detect_data_drift
[2024-11-26T11:59:09.918+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:58:57.177040+00:00 [running]> on host 7f10b2294d44
[2024-11-26T11:59:10.036+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_data_drift' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T11:58:57.177040+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T11:58:57.177040+00:00'
[2024-11-26T11:59:10.135+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:59:10.137+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:59:10.143+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:59:10.144+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:59:10.347+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:59:10.348+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:59:10.353+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:59:10.354+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:59:10.503+0000] {python.py:194} INFO - Done. Returned value was: data_drift_detected
[2024-11-26T11:59:10.504+0000] {python.py:227} INFO - Branch callable return data_drift_detected
[2024-11-26T11:59:10.504+0000] {skipmixin.py:173} INFO - Following branch data_drift_detected
[2024-11-26T11:59:10.536+0000] {skipmixin.py:239} INFO - Skipping tasks [('no_data_drift_detected', -1), ('test_email', -1)]
[2024-11-26T11:59:10.597+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=drift_detection_dag, task_id=detect_data_drift, execution_date=20241126T115857, start_date=20241126T115909, end_date=20241126T115910
[2024-11-26T11:59:10.667+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-26T11:59:10.713+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
