[2024-01-24 15:22:31,013] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:17:22.736757+00:00 [queued]>
[2024-01-24 15:22:31,021] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:17:22.736757+00:00 [queued]>
[2024-01-24 15:22:31,021] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-24 15:22:31,022] {taskinstance.py:1357} INFO - Starting attempt 3 of 6
[2024-01-24 15:22:31,022] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-24 15:22:31,032] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-01-24 15:17:22.736757+00:00
[2024-01-24 15:22:31,037] {standard_task_runner.py:52} INFO - Started process 361 to run task
[2024-01-24 15:22:31,041] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'monitoring_dag', 'detect_data_drift', 'manual__2024-01-24T15:17:22.736757+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmp45e3f_6w', '--error-file', '/tmp/tmp82ip3n_g']
[2024-01-24 15:22:31,042] {standard_task_runner.py:80} INFO - Job 11: Subtask detect_data_drift
[2024-01-24 15:22:31,082] {task_command.py:370} INFO - Running <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:17:22.736757+00:00 [running]> on host 7aa566990013
[2024-01-24 15:22:31,143] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=monitoring_dag
AIRFLOW_CTX_TASK_ID=detect_data_drift
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T15:17:22.736757+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-24T15:17:22.736757+00:00
[2024-01-24 15:22:31,189] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitoring-dag.py", line 69, in _detect_data_drift
    report = data_drift_report.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/suite/base_suite.py", line 249, in json
    self._get_json_content(include_render=include_render, include=include, exclude=exclude, **kwargs),
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/suite/base_suite.py", line 451, in _get_json_content
    res = super()._get_json_content(include_render, include, exclude, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/suite/base_suite.py", line 238, in _get_json_content
    result.update(self.as_dict(include_render=include_render, include=include, exclude=exclude, **kwargs))
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/report/report.py", line 168, in as_dict
    exclude=exclude.get(metric_id),
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/renderers/base_renderer.py", line 47, in render_json
    result = obj.get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/base_metric.py", line 223, in get_result
    raise result.exception
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculation_engine/engine.py", line 42, in execute_metrics
    calculations[metric] = calculation.calculate(context, converted_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculation_engine/python_engine.py", line 88, in calculate
    return self.metric.calculate(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/metrics/data_drift/dataset_drift_metric.py", line 97, in calculate
    agg_data=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculations/data_drift.py", line 448, in get_drift_for_columns
    agg_data=agg_data,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculations/data_drift.py", line 211, in get_one_column_drift
    datetime_column_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/utils/visualizations.py", line 1219, in prepare_df_for_time_index_plot
    prefix, freq = choose_agg_period(df[datetime_name], None)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/utils/visualizations.py", line 1176, in choose_agg_period
    days = (datetime_feature.max() - datetime_feature.min()).days
TypeError: unsupported operand type(s) for -: 'str' and 'str'
[2024-01-24 15:22:31,198] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=monitoring_dag, task_id=detect_data_drift, execution_date=20240124T151722, start_date=20240124T152231, end_date=20240124T152231
[2024-01-24 15:22:31,207] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task detect_data_drift (unsupported operand type(s) for -: 'str' and 'str'; 361)
[2024-01-24 15:22:31,253] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-24 15:22:31,281] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
