[2024-11-26T11:57:06.754+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:56:54.645242+00:00 [queued]>
[2024-11-26T11:57:06.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:56:54.645242+00:00 [queued]>
[2024-11-26T11:57:06.769+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-26T11:57:06.785+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-11-26 11:56:54.645242+00:00
[2024-11-26T11:57:06.793+0000] {standard_task_runner.py:57} INFO - Started process 682 to run task
[2024-11-26T11:57:06.797+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'drift_detection_dag', 'detect_data_drift', 'manual__2024-11-26T11:56:54.645242+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/drift-detection.py', '--cfg-path', '/tmp/tmp8r10iy7f']
[2024-11-26T11:57:06.801+0000] {standard_task_runner.py:85} INFO - Job 67: Subtask detect_data_drift
[2024-11-26T11:57:06.854+0000] {task_command.py:416} INFO - Running <TaskInstance: drift_detection_dag.detect_data_drift manual__2024-11-26T11:56:54.645242+00:00 [running]> on host 7f10b2294d44
[2024-11-26T11:57:06.956+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='drift_detection_dag' AIRFLOW_CTX_TASK_ID='detect_data_drift' AIRFLOW_CTX_EXECUTION_DATE='2024-11-26T11:56:54.645242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-26T11:56:54.645242+00:00'
[2024-11-26T11:57:07.017+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:57:07.018+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:57:07.022+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:57:07.023+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:57:07.126+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:57:07.127+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:57:07.130+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]

[2024-11-26T11:57:07.130+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/numpy/lib/function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

[2024-11-26T11:57:07.237+0000] {python.py:194} INFO - Done. Returned value was: data_drift_detected
[2024-11-26T11:57:07.238+0000] {python.py:227} INFO - Branch callable return data_drift_detected
[2024-11-26T11:57:07.238+0000] {skipmixin.py:173} INFO - Following branch data_drift_detected
[2024-11-26T11:57:07.264+0000] {skipmixin.py:239} INFO - Skipping tasks [('no_data_drift_detected', -1), ('test_email', -1)]
[2024-11-26T11:57:07.308+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=drift_detection_dag, task_id=detect_data_drift, execution_date=20241126T115654, start_date=20241126T115706, end_date=20241126T115707
[2024-11-26T11:57:07.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-26T11:57:07.412+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
