[2024-01-24 15:37:41,854] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:36:36.433675+00:00 [queued]>
[2024-01-24 15:37:41,862] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:36:36.433675+00:00 [queued]>
[2024-01-24 15:37:41,862] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-01-24 15:37:41,863] {taskinstance.py:1357} INFO - Starting attempt 2 of 6
[2024-01-24 15:37:41,863] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-01-24 15:37:41,872] {taskinstance.py:1377} INFO - Executing <Task(BranchPythonOperator): detect_data_drift> on 2024-01-24 15:36:36.433675+00:00
[2024-01-24 15:37:41,877] {standard_task_runner.py:52} INFO - Started process 1209 to run task
[2024-01-24 15:37:41,879] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'monitoring_dag', 'detect_data_drift', 'manual__2024-01-24T15:36:36.433675+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpzrvyp91z', '--error-file', '/tmp/tmplsmj90kr']
[2024-01-24 15:37:41,880] {standard_task_runner.py:80} INFO - Job 51: Subtask detect_data_drift
[2024-01-24 15:37:41,917] {task_command.py:370} INFO - Running <TaskInstance: monitoring_dag.detect_data_drift manual__2024-01-24T15:36:36.433675+00:00 [running]> on host 7aa566990013
[2024-01-24 15:37:41,961] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=monitoring_dag
AIRFLOW_CTX_TASK_ID=detect_data_drift
AIRFLOW_CTX_EXECUTION_DATE=2024-01-24T15:36:36.433675+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-24T15:36:36.433675+00:00
[2024-01-24 15:37:42,002] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 207, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/monitoring-dag.py", line 68, in _detect_data_drift
    report = data_drift_report.as_dict()
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/report/report.py", line 168, in as_dict
    exclude=exclude.get(metric_id),
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/renderers/base_renderer.py", line 47, in render_json
    result = obj.get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/base_metric.py", line 223, in get_result
    raise result.exception
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculation_engine/engine.py", line 42, in execute_metrics
    calculations[metric] = calculation.calculate(context, converted_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculation_engine/python_engine.py", line 88, in calculate
    return self.metric.calculate(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/metrics/data_drift/dataset_drift_metric.py", line 97, in calculate
    agg_data=True,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculations/data_drift.py", line 448, in get_drift_for_columns
    agg_data=agg_data,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/calculations/data_drift.py", line 211, in get_one_column_drift
    datetime_column_name,
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/utils/visualizations.py", line 1219, in prepare_df_for_time_index_plot
    prefix, freq = choose_agg_period(df[datetime_name], None)
  File "/home/airflow/.local/lib/python3.7/site-packages/evidently/utils/visualizations.py", line 1176, in choose_agg_period
    days = (datetime_feature.max() - datetime_feature.min()).days
TypeError: unsupported operand type(s) for -: 'str' and 'str'
[2024-01-24 15:37:42,010] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=monitoring_dag, task_id=detect_data_drift, execution_date=20240124T153636, start_date=20240124T153741, end_date=20240124T153742
[2024-01-24 15:37:42,021] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task detect_data_drift (unsupported operand type(s) for -: 'str' and 'str'; 1209)
[2024-01-24 15:37:42,052] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-01-24 15:37:42,092] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
